### ISSUE TITLE
Succinct Toolchain Installation Issue for the Sample Program

### ISSUE THREAD

**Issue by gokulsan** [succinctlabs/sp1#1011]
Hello Team,

I am setting up the SP1 zkVM first time. It is setup on Ubuntu 24.04 LTS. 

I am getting the following error on running the example Fibanacci Number Proof. 

:~/Code/succinct-sp1/fibonacci/script$ cargo run --release
   Compiling fibonacci-script v0.1.0 (/home/gokul-alex/Code/succinct-sp1/fibonacci/script)

The following warnings were emitted during compilation:
warning: fibonacci-script@0.1.0: fibonacci-program built at 2024-07-02 16:02:04

error: failed to run custom build command for `fibonacci-script v0.1.0 (/home/gokul-alex/Code/succinct-sp1/fibonacci/script)`

Caused by:
  process didn't exit successfully: `/home/gokul-alex/Code/succinct-sp1/fibonacci/script/target/release/build/fibonacci-script-6aab7d622260a064/build-script-build` (exit status: 101)
  --- stdout
  path: "../program"
  cargo::rerun-if-changed=../program/src
  cargo::rerun-if-changed=../program/Cargo.toml
  cargo::rerun-if-changed=../program/Cargo.lock
  cargo:warning=fibonacci-program built at 2024-07-02 16:02:04

  --- stderr
  [sp1] error: override toolchain 'succinct' is not installed: the RUSTUP_TOOLCHAIN environment variable specifies an uninstalled toolchain
  thread 'main' panicked at /home/gokul-alex/.cargo/git/checkouts/sp1-20c98843a1ffc860/b35be42/helper/src/lib.rs:47:9:
  Failed to build `fibonacci-program`.
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by jtguibas** [comment]
Hi, it seems like you did not properly install our custom Rust toolchain. Please refer to https://docs.succinct.xyz/getting-started/install.html.

Let me know if you are having more issues.
