### ISSUE TITLE
Denial of Service on Verifier - Verifier can panic due to assert_eq!() statement

### ISSUE THREAD

**Issue by MauroToscano** [succinctlabs/sp1#1015]
Verifier has a panic that can be triggered by a malicious agent.

This makes any service using SP1 not reliable, since it can be DoS by a malicious payload

This assert should make the proof be false, but not panic. If it's needed for debug it can be changed to an assert_debug

https://github.com/succinctlabs/sp1/blob/14eb569d41d24721ffbd407d6060e202482d659c/core/src/stark/verifier.rs#L54

**Comment by jtguibas** [comment]
Resolved in #1017.
