### ISSUE TITLE
Unused variable `shard_main_datas`

### ISSUE THREAD

**Issue by TomTaehoonKim** [succinctlabs/sp1#1041]
When committing to shards, `commit_data` is appended to `shard_main_datas`. However, `shard_main_datas` is unused.

See https://github.com/succinctlabs/sp1/blob/14eb569d41d24721ffbd407d6060e202482d659c/core/src/utils/prove.rs#L186.

**Comment by jtguibas** [comment]
Hi, this is resolved on the `dev` branch which will be merged to `main` soon.
