### ISSUE TITLE
The usage about the `secp256k1::ecrecover` in `zkvm::precompiles`

### ISSUE THREAD

**Issue by xiyu1984** [succinctlabs/sp1#1078]
I found that all inputs in 'zkvm::io' must be read before calling 'secp256k1::ecrecover' in 'zkvm::precompiles'.

Here's the [example](https://github.com/xiyu1984/ec-recover-sp1/blob/2202c2bc4bf15f9d8781feb03ec86ed64eeac9fa/program/src/main.rs#L12).  The execution will panic at [this line](https://github.com/succinctlabs/sp1/blob/14eb569d41d24721ffbd407d6060e202482d659c/zkvm/precompiles/src/secp256k1.rs#L203) if we prove more than one signature-recovering.  

I think this is due to the following:

```rust
...
unconstrained! {
        let mut buf = [0; 65 + 32];
        let (buf_sig, buf_msg_hash) = buf.split_at_mut(sig.len());
        buf_sig.copy_from_slice(sig);
        buf_msg_hash.copy_from_slice(msg_hash);
        io::write(FD_ECRECOVER_HOOK, &buf);
}

let recovered_bytes: [u8; 33] = io::read_vec().try_into().unwrap();
...
```

The `buf` is written to the end of the `zkvm::io` and if there are still any inputs in the `zkvm::io`, the following line will panic.

The compromise way is that in the `circuit`(in `program`) part, before any execution code, **all of the inputs must be read out first**.

I wonder if there's any other way to solve this problem and if caching all the inputs will make larger circuits.

**Comment by ratankaliani** [comment]
Hey @xiyu1984, thanks for raising this issue.

We now support `secp256k1` acceleration with patches to `ecdsa-core` and `secp256k1`, I'd recommend following the instructions here for Secp256k1 acceleration: https://docs.succinct.xyz/writing-programs/patched-crates.html#secp256k1-acceleration!

The usage of `sp1-lib` is quite advanced, and we generally don't have great support for external usage of this library directly.

You can see an example of the usage in our `patch-testing` example here: https://github.com/succinctlabs/sp1/tree/main/examples/patch-testing

Let me know if you run into any issues!

**Comment by xiyu1984** [comment]
> Hey @xiyu1984, thanks for raising this issue.
> 
> We now support `secp256k1` acceleration with patches to `ecdsa-core` and `secp256k1`, I'd recommend following the instructions here for Secp256k1 acceleration: https://docs.succinct.xyz/writing-programs/patched-crates.html#secp256k1-acceleration!
> 
> The usage of `sp1-lib` is quite advanced, and we generally don't have great support for external usage of this library directly.
> 
> You can see an example of the usage in our `patch-testing` example here: https://github.com/succinctlabs/sp1/tree/main/examples/patch-testing
> 
> Let me know if you run into any issues!

Thanks a lot. 
I found the patches ([signatures](https://github.com/sp1-patches/signatures) and [rust-secp256k1](https://github.com/sp1-patches/rust-secp256k1)) yesterday and substituted the previous one in `sp1-lib` with them. 

Until now, they work well.

All the best~
