### ISSUE TITLE
[docs] Wrong default and path in quickstart guide and program does not allow for proofs for n larger 186  

### ISSUE THREAD

**Issue by nashqueue** [succinctlabs/sp1#1144]
I am just starting off with the [quickstart guide](https://docs.succinct.xyz/getting-started/quickstart.html), and I had some trouble changing the value of n in the Fibonacci sequence. 

Path mentioned in the docs: `script/src/main.rs`
The actual path: `script/src/bin/prove.rs`

It says the default is 186, although it currently is 20.

Also, it says that n larger 186 is supported, but the program throws an error for that case. Here is a screenshot for n=190
![image](https://github.com/user-attachments/assets/7826e2be-943e-4a14-8be5-38c15e54524c)

**Comment by ratankaliani** [comment]
This was resolved a few months ago in the book: https://docs.succinct.xyz/getting-started/quickstart.html
