### ISSUE TITLE
Question: minimum shards in the generated proof (proof.shard_proofs)

### ISSUE THREAD

**Issue by eason1981** [succinctlabs/sp1#1257]
Hi, I have a question about the sp1 sharding, I try to use [zkvm-perf](https://github.com/succinctlabs/zkvm-perf) to benchmark for fibonacci (with sp1 `v1.0.1` and it has the same shard number as the proof result when switching to sp1 main branch). I set `SHARD_SIZE = 1 << 20`.
Seems it could not generate less than 3 shards (proof.shard_proofs) even if I changed the input `n` to 1 for fibonacci. And I found that the execute shards are added in these 3 places of the code:

https://github.com/succinctlabs/sp1/blob/main/core/src/runtime/mod.rs#L1139
https://github.com/succinctlabs/sp1/blob/main/core/src/runtime/mod.rs#L1146
https://github.com/succinctlabs/sp1/blob/v1.0.1/core/src/utils/prove.rs#L268

Is it by design? Or I missed or used some wrong configurations or options to generate proofs, thanks for any helps!

**Comment by nhtyy** [comment]
Closing for now as likely outdated, feel free to reopen.
