### ISSUE TITLE
Incorrect attribution of code and copyright

### ISSUE THREAD

**Issue by Riderfighter** [succinctlabs/sp1#1282]
Hello team! I noticed that proper attribution to Risc0 and Valida were removed along with the copyright from files where code was taken from the previously stated projects.

I suggest remedying this as this is a direct violation of their licenses and copyright.

**Comment by ewynx** [comment]
+1

**Comment by jtguibas** [comment]
Added acknowledgments back to README. We're very happy to provide proper attribution, please let us know if there are particular places in the codebase that come to mind and feel free to make PRs.
