### ISSUE TITLE
Wrong comment of struct in `bn254.rs`

### ISSUE THREAD

**Issue by NikolayKostadinov21** [succinctlabs/sp1#1300]
# Problem
The comment over the [`Bn254AffinePoint`](https://github.com/succinctlabs/sp1/blob/57867346f086a0c15e0503d693d897bda6bf06b0/zkvm/lib/src/bn254.rs#L10) struct in the `bn254.rs` [file](https://github.com/succinctlabs/sp1/blob/main/zkvm/lib/src/bn254.rs) was mistakenly left `/// An affine point on the BLS12-381 curve.`:
https://github.com/succinctlabs/sp1/blob/57867346f086a0c15e0503d693d897bda6bf06b0/zkvm/lib/src/bn254.rs#L7-L10
# Solution
It should be:
`/// An affine point on the BN-254 curve.`

**Comment by ratankaliani** [comment]
Resolved in https://github.com/succinctlabs/sp1/pull/1310, thanks!
