### ISSUE TITLE
Open-source CPU targets

### ISSUE THREAD

**Issue by taqtiqa-mark** [succinctlabs/sp1#1338]
Are any of the following open-source CPUs targets for SP1?

Specifically, should I ever expect that SP1 will run on, say, the Berkeley/SiFive Rocket [rv32ima](https://github.com/chipsalliance/rocket-tools/blob/master/build-rv32ima.sh), etc

- [ ] Berkeley/SiFive Rocket - https://github.com/chipsalliance/rocket-chip
- [ ] Bluespec Flute - https://github.com/bluespec/Flute
- [ ] OpenHardware Group CVA6 - https://github.com/openhwgroup/cva6.git (a.k.a. ETH Zurich Ariane)
- [ ] PicoRV32 - https://github.com/YosysHQ/picorv32/tree/main
  - [RV32im instructions](https://github.com/YosysHQ/picorv32/tree/main#building-a-pure-rv32i-toolchain)

**Comment by nhtyy** [comment]
Hi thank you for the filling this issue. The VM/runtime can be compiled to any target supported by cargo, and at the moment we have no plans to implement proving over any other ISA.
