### ISSUE TITLE
Segmentation Fault in sp1up, while attempting install.

### ISSUE THREAD

**Issue by dominic-leastauthority** [succinctlabs/sp1#1355]
I installed `sp1up` following the installation instructions, sourced the updated `.bashrc` and then run `sp1up' it says it's downloading `cargo-prove` and `rust toochain` which appear to work but then it fails with this error

```
/home/dominic/.sp1/bin/sp1up: line 337: 26591 Segmentation fault      (core dumped) "$@"
sp1up: command failed: /home/dominic/.sp1/bin/cargo-prove prove install-toolchain
``` 

this is on linux, if that helps

**Comment by jtguibas** [comment]
Hi, I think this is related to https://github.com/rust-lang/rust/issues/100110. We are thinking of compiling the CLI to a cross platform target to avoid this issue,

For now if you build the CLI from source, it should work on your platform.

**Comment by jtguibas** [comment]
Are you on x86 linux?

**Comment by dominic-leastauthority** [comment]
> Are you on x86 linux?
yes.

thanks, I shall try compiling it

**Comment by dominic-leastauthority** [comment]
It builds fine, and I am able to run `./target/debug/cargo-prove` but if I run the tests it eventually fails because scuccinct is not installed

I read all the files such as `DEVELOPMENT.md` but I didn't see anything about how to install the local build. How do I do that? (sorry I am new to rust)

```
error: failed to run custom build command for `fibonacci-script v0.1.0 (/home/dominic/c/sp1/fibonacci/script)`

Caused by:
  process didn't exit successfully: `/home/dominic/c/sp1/fibonacci/target/release/build/fibonacci-script-21c49dde28a8d5f4/build-script-build` (exit status: 1)
  --- stdout
  cargo::rerun-if-changed=/home/dominic/c/sp1/fibonacci/program/src
  cargo::rerun-if-changed=/home/dominic/c/sp1/fibonacci/program/Cargo.toml
  cargo:rerun-if-changed=/home/dominic/c/sp1/fibonacci/Cargo.lock
  cargo:rerun-if-changed=/home/dominic/c/sp1/fibonacci/lib
  cargo:rerun-if-changed=/home/dominic/c/sp1/fibonacci/lib

  --- stderr
  [sp1]  error: override toolchain 'succinct' is not installed: the RUSTUP_TOOLCHAIN environment variable specifies an uninstalled toolchain
warning: build failed, waiting for other jobs to finish...
```

**Comment by jtguibas** [comment]
You can follow the instructions here: https://docs.succinct.xyz/getting-started/install.html#option-2-building-from-source.

**Comment by jtguibas** [comment]
If you need more help, feel free to DM me on Telegram: @jtguibas.

**Comment by dominic-leastauthority** [comment]
It builds fine, and I am able to run `./target/debug/cargo-prove` but if I run the tests it eventually fails because scuccinct is not installed

I read all the files such as `DEVELOPMENT.md` but I didn't see anything about how to install the local build. How do I do that? (sorry I am new to rust)

```
error: failed to run custom build command for `fibonacci-script v0.1.0 (/home/dominic/c/sp1/fibonacci/script)`

Caused by:
  process didn't exit successfully: `/home/dominic/c/sp1/fibonacci/target/release/build/fibonacci-script-21c49dde28a8d5f4/build-script-build` (exit status: 1)
  --- stdout
  cargo::rerun-if-changed=/home/dominic/c/sp1/fibonacci/program/src
  cargo::rerun-if-changed=/home/dominic/c/sp1/fibonacci/program/Cargo.toml
  cargo:rerun-if-changed=/home/dominic/c/sp1/fibonacci/Cargo.lock
  cargo:rerun-if-changed=/home/dominic/c/sp1/fibonacci/lib
  cargo:rerun-if-changed=/home/dominic/c/sp1/fibonacci/lib

  --- stderr
  [sp1]  error: override toolchain 'succinct' is not installed: the RUSTUP_TOOLCHAIN environment variable specifies an uninstalled toolchain
warning: build failed, waiting for other jobs to finish...
```

**Comment by dominic-leastauthority** [comment]
It builds fine, and I am able to run `./target/debug/cargo-prove` but if I run the tests it eventually fails because scuccinct is not installed

I read all the files such as `DEVELOPMENT.md` but I didn't see anything about how to install the local build. How do I do that? (sorry I am new to rust)

```
error: failed to run custom build command for `fibonacci-script v0.1.0 (/home/dominic/c/sp1/fibonacci/script)`

Caused by:
  process didn't exit successfully: `/home/dominic/c/sp1/fibonacci/target/release/build/fibonacci-script-21c49dde28a8d5f4/build-script-build` (exit status: 1)
  --- stdout
  cargo::rerun-if-changed=/home/dominic/c/sp1/fibonacci/program/src
  cargo::rerun-if-changed=/home/dominic/c/sp1/fibonacci/program/Cargo.toml
  cargo:rerun-if-changed=/home/dominic/c/sp1/fibonacci/Cargo.lock
  cargo:rerun-if-changed=/home/dominic/c/sp1/fibonacci/lib
  cargo:rerun-if-changed=/home/dominic/c/sp1/fibonacci/lib

  --- stderr
  [sp1]  error: override toolchain 'succinct' is not installed: the RUSTUP_TOOLCHAIN environment variable specifies an uninstalled toolchain
warning: build failed, waiting for other jobs to finish...
```

sorry I accidentially closed it

**Comment by dominic-leastauthority** [comment]
those instructions are out of date. it says `cd cli` but there is no cli directory. I presume it should be `cd crates/cli`

**Comment by dominic-leastauthority** [comment]
I'm still missing `succinct` how do I install that manually?

**Comment by jtguibas** [comment]
![Screenshot 2024-08-27 at 11 12 57 AM](https://github.com/user-attachments/assets/8bfb4454-83ce-496e-a182-7acda66d3a7b)

The instructions should be fixed now, sorry about that.

For installing the `succinct` toolchain, if you run `cargo prove install-toolchain` or `cargo prove build-toolchain` it should install it.

If that's not working it sounds like there is something weird going on with your Rust installation or setup, if you run it on a fresh machine or a VM it will work.

**Comment by thorstenhirsch** [comment]
You know that Option 1 (precompiled binary) still runs on segmentation fault, right? I'm on Ubuntu 24.04.1 (x64) in VirtualBox.
```
[   34.687759] tokio-runtime-w[2593]: segfault at 2043c0 ip 000074552343ba26 sp 00007455239fe7d8 error 4 in libc.so.6[745523428000+188000] likely on CPU 1 (core 1, socket 0)
[   34.687772] Code: 48 03 04 25 00 00 00 00 c3 66 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 48 8b 05 3d 75 1c 00 48 8b 0d be 73 1c 00 64 48 8b 00 <48> 8b 00 48 8b 70 38 48 8d 96 00 01 00 00 64 48 89 11 48 8b 78 40
```

**Comment by koxu1996** [comment]
Same on Debian.

**Comment by byhashdong** [comment]
Same issue on `Ubuntu24.04` on `AMD Ryzen 7 5700U`

**Comment by leruaa** [comment]
We will publish a release that fix this issue soon, but in the meantime as a workaround you can install SP1 with the following command:

```
SP1UP_VERSION=v3.0.1-alpha-b976ea6e sp1up
```

It will uses a (fixed) pre-release. Please lmk if it works.
