### ISSUE TITLE
Question: I/O and unconstrained mode

### ISSUE THREAD

**Issue by mrain** [succinctlabs/sp1#1499]
I'm recently working on some ZK project using SP1, and find out that for my sp1 program, I/O and (de)serializations take quite a lot of cycles. Main reason is that, many structs may have some complex customized (de)serialization, e.g. [in arkworks](https://docs.rs/ark-serialize/latest/ark_serialize/) elliptic curve points are usually serialized in compressed form to ensure some extra property/save bandwidth.

I was trying to avoid these unnecessarily complex overhead. ZK programs are usually proving some relation among the public inputs, with the help of some witnesses. During I/O, we cannot really avoid the (de)sers for public inputs because they should be bounded. But that's not the case for witnesses, as we only have to show the existence of such witnesses. So my idea is, we could put the I/O of witnesses in the unconstrained mode, but it's currently not allowed. I'm wondering that whether we could have something like `unconstrained_read()` for sp1?

**Comment by ctian1** [comment]
You could use read_slice outside of unconstrained mode and then deserialize in unconstrained mode and validate. I think that's the best it could get.
