### ISSUE TITLE
Question: LLVM 

### ISSUE THREAD

**Issue by UIZorrot** [succinctlabs/sp1#1545]
SP1 claimed to be friendly for any LLVM-compiled language, I wonder how can I using another languauge to wirte SP1 specification, like C++. If I can't do that, it will be helpful if you told me about how to adapt more LLVM supported frontend (It may be hard, but it's helpful if you guys can share some insight)

**Comment by ctian1** [comment]
If it compiles to RISC-V, it should be possible. We have some [syscalls we call at the end of the program](https://github.com/succinctlabs/sp1/blob/dev/crates/zkvm/entrypoint/src/lib.rs#L56) to commit to the public values hash, and we use syscalls for precompiles and I/O.
