### ISSUE TITLE
Question: Why use gnark?

### ISSUE THREAD

**Issue by adust09** [succinctlabs/sp1#1676]
Hi team!

What is described [here](https://docs.succinct.xyz/onchain-verification/getting-started.html?highlight=recursion#generating-sp1-proofs-for-onchain-verification) is understandable, but why use gnark, which seems to add overhead to running FFI?

[In practice](https://docs.succinct.xyz/generating-proofs/proof-types.html), groth16/plonk mode affects the proof time; I felt that the FFI process was the bottleneck here.
I thought we could get more speed by replacing groth16/Plonk with a Rust implementation.

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by jtguibas** [comment]
The main bottleneck is actually loading the R1CS/proving key right now and witness generation. I don't think there is much FFI overhead.
