### ISSUE TITLE
Question: Is cycle count in SP1 correspond to total or user cycles in RISC0?

### ISSUE THREAD

**Issue by yaziciahmet** [succinctlabs/sp1#1682]
Hey guys. It is not clear to me whether the cycle count in SP1 correspond to total or user cycles in RISC0. Would appreciate a clarification.

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
