### ISSUE TITLE
SP1 verifier on CosmWasm (challenges and impl questions)

### ISSUE THREAD

**Issue by hu55a1n1** [succinctlabs/sp1#1704]
Hi SP1 Team!

Thank you for this wonderful project! I’m working on a CosmWasm smart contract for SP1 verification. I’ve encountered several challenges so far, and I would like to get your opinion on the best way forward.

## Challenges encountered
- Contract Size: The smart contract is currently too large to deploy on CosmWasm chains due to a 800KB hard limit on contract size. (For reference, a CosmWasm verifier contract using the `sp1-prover` and `sp1-stark` crates is already 7.8MB). Also, there don’t seem to be many features available to disable unnecessary or unused (w.r.t. verification) dependencies within these crates.
- Verifier Crate: There isn’t a separate light-weight verifier crate. I think this is related to https://github.com/succinctlabs/sp1/issues/636. 
- FFI Dependencies: Since this is a wasm target, I'd like to avoid FFI and std. And IIUC, the verifier code for both the groth16 and PLONK provers currently depends on gnark via FFI and also uses the file-system. 

## Proposal
Given these contraints, I see 2 options - 
1. Extract the verifiers into a separate crate, with all FFI/std code feature gated. And use the compress verfier - I noticed that compress isn't EVM compatible but I presume it would work on CosmWasm? 
2. Or, write a custom rust verifier from scratch based on the solidity verifier code that gnark generates.

Do you have other suggestions? What would be the best way to implement this? 
Any advice or insights would be greatly appreciated. Thanks in advance!

**Comment by yuwen01** [comment]
Hi @hu55a1n1, just wanted to let you know that I merged the lightweight verifier crate, which should work in your use case. Let me know if you have any issues getting it running!

**Comment by hu55a1n1** [comment]
Hi! Just wanted to report that the new verifier crate works out-of-the-box for us in CosmWasm! Thank you @puma314 and @yuwen01! 🫶 

Since there are no BN254 precompiles on CosmWasm, verifying the [test proof from here](https://github.com/succinctlabs/sp1/pull/1685/files#diff-22ff3308ad71b54eec6c1a0ae2121f267e55798e242443d34cb5ef06057a2e96R5-R26) takes a good 21.5M gas. For context the block gas limit on neutron (a prod CosmWasm chain) is 30M. 

So we're thinking of adding a BLS12-381 based Groth16 prover/verifier to SP1 (because CosmWasm does have precompiles for that). Either that, or we get CosmWasm precompiles for BN254 🤞 (which seems like it'll be more difficult because it requires chain upgrades, etc.). Will open a follow-up issue with an impl prop. (Happy to work on that although I am not much of a ZK dev - but hoping to get your inputs/guidance 🙏).
