### ISSUE TITLE
Question / Idea: example to showcase "proof of having some secret"

### ISSUE THREAD

**Issue by grasphoper** [succinctlabs/sp1#1729]
One of the commonly advertised use cases for ZKProofs is the following:
I can prove to you that I have some secret `S`, where `f(S) = X`, without revealing the secret to you.

Most of the examples in the `examples/` directory showcase "proving a result of some computation, so that the verifier doesn't have to redo the calculation again".

On the secrets front, there's the `rsa` example which comes close to what I have in mind but is different. In the `rsa` example, inside of the "program" which is our provable computation, we do roughly the following:

```rust
let pk = read_public_key();
let sig = read_signature();
let msg = read_signed_msg();
let valid_sig = RsaVerifySig(pk, sig, msg);
sp1_zkvm::io::commit(&valid_sig);
```

However, one can check whether an RSA signature is valid without using ZKProofs. I think it'd be interesting to showcase the ability of ZKProof to not reveal anything secret through proving roughly the following:

```rust
let public_key = read_public_key();
let private_key = read_private_key();
let valid_pair = public_key.Eq(RsaGeneratePublicKey(private_key));
sp1_zkvm::io::commit(&valid_pair);
```

This way we could prove that we have access to a `private_key` without generating any signatures through RSA.

Thanks for reading through my issue, let me know what you think!

**Comment by nhtyy** [comment]
Thank you for the suggestion, however at the moment we aren't accepting any new examples.
