### ISSUE TITLE
Why while installing it is showing a segmentation fault ? I have all the requirements installed and checked. 

### ISSUE THREAD

**Issue by Skythrill256** [succinctlabs/sp1#1741]
![241102_18h57m24s_screenshot](https://github.com/user-attachments/assets/25445658-bebf-4e1f-b7cb-6f8ab25215fa)

**Comment by mahmudsudo** [comment]
Try the other forms of installation

**Comment by joske** [comment]
I have the same issue on Arch linux. It does install inside a ubuntu 24.04 docker container. Not sure if this will lead to other issues later.

**Comment by jtguibas** [comment]
@leruaa

**Comment by leruaa** [comment]
@mahmudsudo @joske We will publish a release that fix this issue soon, but in the meantime as a workaround you can install SP1 with the following command:

```
SP1UP_VERSION=v3.0.1-alpha-b976ea6e sp1up
```

It will uses a (fixed) pre-release.
