### ISSUE TITLE
Prebuilt proofs for examples

### ISSUE THREAD

**Issue by zyedidia** [succinctlabs/sp1#1766]
### Component

Other (please describe)

### Describe the feature you would like

I'm interested in benchmarking proof verification performance for groth16 and plonk on various machines and execution environments. The examples in this repository seem like a nice set of programs to experiment with. However, generating the proofs is quite resource-intensive and time-consuming. If you happen to already have groth16 and plonk proofs for some/all of the examples it would be great if these could be uploaded somewhere. I would only need the `proof-with-pis.bin` file, plus the associated ELF (looks like prebuilt ELFs already exist for all examples). Thanks!

**Comment by yuwen01** [comment]
As a band aid, there are some pre-generated proofs I use for testing here: https://github.com/succinctlabs/sp1/tree/dev/crates/verifier/test_binaries. You can see the tests here for an example of how to verify them.

If these suffice then I can close the issue, unless you'd want more serialized core /  compressed proofs or proofs for more varied programs.

**Comment by zyedidia** [comment]
Thanks! I did manage to generate groth16/plonk proofs for the fibonacci example, but I would ideally like to benchmark with a larger set of more varied programs.

**Comment by nhtyy** [comment]
Closing as we will likely not being maintaining example proofs in this repo
