### ISSUE TITLE
A feature to add syscall precompiles

### ISSUE THREAD

**Issue by kimurayu45z** [succinctlabs/sp1#1775]
### Component

sp1-sdk, sp1-zkvm

### Describe the feature you would like

When we consider to build a smart contract VM (like Ethereum Virtual Machine) with SP1 zkVM, there are two theoretical ways:

1. Compiling smart contract as a program being run in zkVM
2. Compiling smart contract as conventional ways and compiling smart contract VM as a program being run in zkVM

To keep the consistency with conventional smart contract compiler ecosystem, the 2nd would be better. (There is also a possibility of the 1st being better than 2nd due to the proof sizes.)
However, in either ways, there is a requirement to access database and storage.
If we implement database and storage stuff in zkVM, the proof size would be significantly large, so I think it would be better to add a feature to add syscall precompiles for stuff like database/storage access. The diff of the storage can be input/output of the proof.

**Comment by kimurayu45z** [comment]
https://github.com/succinctlabs/sp1/blob/4503ebda58adc82452dae48a5d57fd7752da1d40/crates/core/machine/src/syscall/precompiles/README.md

**Comment by kimurayu45z** [comment]
Isn't there a way to add precompiles without editing sp1 repository directly?

**Comment by nhtyy** [comment]
Thank you for the filling the issue but for now this feature is not planned, In the future we may revisit it.
