### ISSUE TITLE
Publish proof as EIP-4844 BLOB

### ISSUE THREAD

**Issue by JKincorperated** [succinctlabs/sp1#1777]
### Component

sp1-sdk, Other (please describe)

### Describe the feature you would like

On chain verification via solidity is slow and inefficient, a form of Proof of Equivalence can be used to convert the proof into a (eip-4844) blob and verify it for cheaper using the point evaluation precompile rather than pure solidity.

### Additional context

https://www.eip4844.com/
https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4844.md
https://www.evm.codes/precompiled?fork=cancun#0x0a
https://ethresear.ch/t/easy-proof-of-equivalence-between-multiple-polynomial-commitment-schemes-to-the-same-data/8188

**Comment by nhtyy** [comment]
Thank you for suggestion but at the moment we don't see calldata costs as too big of a bottleneck, closing as not planned
