### ISSUE TITLE
verify_gnark_proof can cause panic if the proof is wrong

### ISSUE THREAD

**Issue by 0xSasaPrsic** [succinctlabs/sp1#1830]
### Component

sp1-sdk

### Have you ensured that all of these are up to date?

- [X] SP1 SDK
- [ ] cargo prove CLI/sp1up

### Operating System

None

### Describe the bug

The `verify_gnark_proof` [function](https://github.com/succinctlabs/sp1/blob/dev/crates/verifier/src/groth16/mod.rs#L95) can cause a panic if the proof is wrong as it uses `unwraps`.
The function already returns a `Result<(), Groth16Error>` and in case of wrong proof it should return an error and not panic.
All `.unwrap() ` calls should be removed.

**Comment by fedemagnani** [comment]
Hi, can I take this?
