### ISSUE TITLE
Showcase Request: Ethereum ZK Light Client with Helios

### ISSUE THREAD

**Issue by puma314** [succinctlabs/sp1#229]
ZK light clients for trust-minimized bridging are one of the important use-cases of ZKPs. There are several ZK Ethereum Light Client implementations that exist, written in [Circom](https://github.com/succinctlabs/telepathyx) and other ZK-specific languages, but they are hard to modify and decipher.

[Helios](https://github.com/a16z/helios) is a Rust implementation of an Ethereum light client that can be utilized inside SP1 to create a maintainable, readable Ethereum ZK Light Client.

**Comment by makluganteng** [comment]
Hi im interested in trying this out

**Comment by mahmudsudo** [comment]
can i take on this ?

**Comment by ameya-deshmukh** [comment]
Hey will let you know if I was able to make any progress on this by the end of the weekend. If not, please take it up :)

**Comment by mahmudsudo** [comment]
I guess i am free to take this then

**Comment by mahmudsudo** [comment]
Thanks , i would be reaching out soon

**Comment by hydrogenbond007** [comment]
Hey @puma314  is the work on this going on? I was working on building a relay bridge that transfers calldata. Been using helios but it adds additional overhead for devs to verify the state transitions of one chain on another. 
would be cool to explore the zk light client

**Comment by mahmudsudo** [comment]
@hydrogenbond007 yes work is going on this issue , was busy the past few days

**Comment by imotai** [comment]
Any updates about this issue? I am very interested in the ethereum zk light client.

**Comment by mahmudsudo** [comment]
almost done with it
