### ISSUE TITLE
Precompile: Add secp256r1 precompiles

### ISSUE THREAD

**Issue by puma314** [succinctlabs/sp1#230]
SP1 already has support for secp256k1 precompiles used in ECDSA signature verification. It would be good to add similar precompiles for secp256r1. This would involve

- implementing the secp256r1 parameters, similar to secp256k1 parameters
- adding a new chip with the secp256r1 parameters
- creating extern syscalls to utilize these new precompiles
- writing tests for these syscalls to verify they work correctly

The precompile system of SP1 is not well documented at present, so this would require the contributor to be able to figure out how things work with minimal documentation.

**Comment by shreyas-londhe** [comment]
I'm interested in working on this!

**Comment by nfurfaro** [comment]
I'm interested in tackling this!
