### ISSUE TITLE
Showcase Request: Optimized Tendermint ZK Light Client

### ISSUE THREAD

**Issue by puma314** [succinctlabs/sp1#233]
Right now, the Tendermint example program verifies all signatures in a block. However, it's performance can significantly improved by early exiting from the verification of signatures once enough of the stake weight has been verified (2/3).

This would involve modifying the Tendermint-rs library to early exit and also creating a utility method for retrieving the signatures from top-validators by stake weight.

**Comment by Redidacove** [comment]
I am new to this, but I know rust can you please point out which part of code I need to modify and what changes are required and some resources to help me do it would be great. @puma314

**Comment by mahmudsudo** [comment]
i will take on this
