### ISSUE TITLE
Bug: Building from source doesn't work

### ISSUE THREAD

**Issue by puma314** [succinctlabs/sp1#241]
Copied from an issue in the [SuccinctX repository](https://github.com/succinctlabs/succinctx/issues/360).

> I tried building SP1 from source, it seems like it's currently not possible:
>
> fatal: repository 'https://github.com/succinctlabs/rust/' not found
>
> See here:
>
> https://github.com/succinctlabs/sp1/blob/54b64b646d18cabef3307bb90167d23470736dc3/cli/src/commands/build_toolchain.rs#L38

**Comment by puma314** [comment]
I just made our [Rust fork](https://github.com/succinctlabs/rust) public, so I believe re-running this command should work?

**Comment by jtguibas** [comment]
Closing as resolved as making our rust fork public seems to haved fixed it. Thanks for the issue @tumberger!
