### ISSUE TITLE
Fibonacci example in SP1 Book Quickstart hits overflow with `i32`

### ISSUE THREAD

**Issue by dr-frmr** [succinctlabs/sp1#244]
Going through the quickstart [here](https://succinctlabs.github.io/sp1/getting-started/quickstart.html), I noticed that the Fibonacci program uses `i32` numbers for `a` and `b`, and in the default number of runs (500) this results in major overflow. I was concerned that the proof had an issue until I saw that the program was using `i32`. I also noticed that the values in the quickstart output didn't match what I actually got -- maybe they were generated when the code was slightly different? Also, the quickstart claims that a `proof-with-pis.json` file will be generated, which should say `proof-with-io.json` I think.

With the current code, the output will only be "correct" for the first few dozen fibonacci numbers. If `a` and `b` are typed as `u128`, it will work up to n=186. To get past there, need to use BigInt or something like that, but I ran into a bunch of `rust-lld` errors when I tried to add that library to the example.

I understand if this is considered okay for the example, given that the program technically still does the 'work' involved in calculating the numbers. It's nice that the example code is simple and doesn't use any libraries. It was just a bit confusing seeing the "wrong" values pop out. Maybe switching to `u128` and a simple disclaimer for n>186 would suffice?

**Comment by puma314** [comment]
Oh yes, thank you for noticing all of this! That's a good callout and I'll change the default example to have much smaller `n`. 

Yes the `BigInt` library is a bit problematic because of some linking errors--we are looking into that (or considering patching it with our existing precompiles, which should be straightforward).

**Comment by dr-frmr** [comment]
Ok, made a fix PR #245

**Comment by jtguibas** [comment]
Closing due to #245.
