### ISSUE TITLE
support stable compiler on tool chain with prebuilt binaries in mac

### ISSUE THREAD

**Issue by rkdud007** [succinctlabs/sp1#260]
In mac, if instaling through 
```
curl -L https://sp1.succinct.xyz | bash
```
get rustc --version : [0.](https://github.com/succinctlabs/sp1/blob/main/rust-toolchain)

want it to be up with stable version :)

**Comment by kevjue** [comment]
@rkdud007 - The mac toolchain build should be updated now to rustc 1.75.  Please rerun your [`sp1up` script](https://succinctlabs.github.io/sp1/getting-started/install.html#option-1-prebuilt-binaries-recommended).

I'm going to close this issue.  Feel free to re-open if you still have issues!
