### ISSUE TITLE
Has anyone able to successfully run it on MacOS?

### ISSUE THREAD

**Issue by chowdhury-bc** [succinctlabs/sp1#293]
## Issue
sp1up: installing sp1 (version nightly, tag nightly)
sp1up: downloading latest cargo-prove
curl: (7) Failed to connect to pub-e4d9616fb885415597ff4c4d2b476ffb.r2.dev port 443: Connection refused

sp1up: command failed: download https://pub-e4d9616fb885415597ff4c4d2b476ffb.r2.dev/cargo_prove_nightly_darwin_amd64.tar.gz

## env
macOS ventura 13.0.1

## steps taken
tried with both option for installation but no luck. 
tried brew update, reinstall openssl@1.1, rebooting etc

**Comment by ctian1** [comment]
Thanks for the issue! Sorry you ran into that, it's definitely something we need to fix. In the meantime, did you try `brew install openssl@3` + the manual installation?

**Comment by jtguibas** [comment]
Hi chowdhurry, when you open the download link what happens? I have seen this issue in the past without someone who's malware preventer stopped them from accessing the download URL.

**Comment by nfurfaro** [comment]
Pretty sure I had this happen on both Mac OS and Linux. 
I believe the issue was simply that I had not sourced my shell  after installing via cURL, but before running `sp1up`.
In my case, this meant running 'source /Users/furnic/.config/fish/config.fish' as directed.

**Comment by bogatyy** [comment]
FWIW I have it working on MacOS, latest MacBook Pro (M3).
Have the full Fibonacci example working, proof generation and everything.

**Comment by ctian1** [comment]
Should be fixed now.
