### ISSUE TITLE
Does sp1 support recursive verification?

### ISSUE THREAD

**Issue by jimzk** [succinctlabs/sp1#320]
I am trying to do recursive verification (verify a proof in the other proof).

I write a [recursive proof demo](https://github.com/jimzk/sp1-recursive) according to my understanding of sp1, but seems the verification is always successful even I give a wrong variable to stdin. And it panics when I try to read something from `proof.stdout`.

In my demo, [riscv32im-succinct-zkvm-elf-plain](https://github.com/jimzk/sp1-recursive/blob/main/program/elf/riscv32im-succinct-zkvm-elf-plain) is plain fibonacci verification while [riscv32im-succinct-zkvm-elf](https://github.com/jimzk/sp1-recursive/blob/main/program/elf/riscv32im-succinct-zkvm-elf) is recursive ELF that verify the other proof.

Do I get something wrong? Or sp1 does not support recursive proof? If not, could someone share an example? Thanks.

**Comment by jtguibas** [comment]
Hi, we have a prototype for recursive proof, but it is still WIP.
