### ISSUE TITLE
Rand: How does it work for hashmaps

### ISSUE THREAD

**Issue by ValarDragon** [succinctlabs/sp1#333]
How does Rand work for Sp1?

We weren't sure at the workshop. Are the random bytes hardcoded for now?

Should this be based on repeated (non-cryptographic) hashing of the public input? That way we can get deterministic traces, but still not-so-vulnerable worst case performance for things like Hashmap insertion

**Comment by matthiasgoergens** [comment]
If you get bad random numbers for your hash table, it's still correct, just slow.

So a malicious prover would only hurt themselves with longer run times, and thus longer traces, and thus longer proving times.

You could make the random numbers used here completely unconstrained to be picked at will by the prover. (But just using some hard coded random seed that's always the same is also fine, you are unlikely to hit the worst case unless you are actively trying.)

**Comment by ValarDragon** [comment]
> So a malicious prover would only hurt themselves with longer run times, and thus longer traces, and thus longer proving times.

Right but the concern isn't a malicious prover, its a prover proving another party's workloads e.g. any ZKVM!

**Comment by matthiasgoergens** [comment]
Wouldn't you charge the other guy eg by the CPU cycle, anyway?

**Comment by jtguibas** [comment]
We now use deterministic randomness using this syscall: 

https://github.com/succinctlabs/sp1/blob/14eb569d41d24721ffbd407d6060e202482d659c/zkvm/entrypoint/src/syscalls/sys.rs#L27.

Hashmaps use the syscall to source randomness.
