### ISSUE TITLE
Precompile: BLS-12-381 operations

### ISSUE THREAD

**Issue by S1nus** [succinctlabs/sp1#334]
**Overview**
Create a precompile for curve operations and pairings

**Use-Cases**
- Beacon chain signatures
- Verifiers for other proof systems
- 4844 integration

**Prior Art**
[Starky implementation by Electron Labs](https://github.com/Electron-Labs/starky_bls12_381)
[RNS Arithmetic](https://eprint.iacr.org/2022/1470)
[Fast Pairings in ZK](https://github.com/axiom-crypto/halo2-lib/issues/101)

**Comment by jtguibas** [comment]
We have added support for basic BLS operations now, but we are still working on accelerating pairings.
