### ISSUE TITLE
New Error with `cargo-prove prove install-toolchain`

### ISSUE THREAD

**Issue by Demian101** [succinctlabs/sp1#338]
```bash
$ sw_vers
ProductName:		macOS
ProductVersion:		14.2.1
BuildVersion:		23C71

$ uname -m
arm64

$ openssl --version
OpenSSL 1.1.1w  11 Sep 2023

$ rustc --version
rustc 1.74.1 (a28077b28 2023-12-04)
```
<img width="889" alt="image" src="https://github.com/succinctlabs/sp1/assets/33189338/81b27bcf-8179-49ae-9197-b1c29409c44c">

**Comment by puma314** [comment]
@jtguibas do you have an idea of what might be happening here? Also @Demian101 I do think we have versions built for Mac with ARM so it's confusing that sp1up doesn't work.

**Comment by Demian101** [comment]
By test `ssh -T git@github.com` , I think there some thing wrong with my ssh.

now I fix it, thanks for that !
