### ISSUE TITLE
Fibonacci example for large N

### ISSUE THREAD

**Issue by bogatyy** [succinctlabs/sp1#361]
My goal is to generate a proof for a sufficiently computationally expensive statement.
To this end, I'm increasing the `N` in the [Fibonacci example](https://succinctlabs.github.io/sp1/getting-started/quickstart.html).

For `N << 10^6`, proof generation finishes quickly.
For `N ~= 10^6`, proof generation takes ~1 minute and peaks at `30 GB` RAM usage.
For `N ~= 10^7`, it crashes with OOM (using up `55 GB` right before the crash).

Seems surprising given that `N=10^7` Fibonacci should be a much simpler task than running reth? Any guesses why the crash?
Macbook Pro, M3 Max, 36 GB RAM.

**Comment by bogatyy** [comment]
CC @jtguibas as the author of the Fibonacci example :)

**Comment by jtguibas** [comment]
Hi @bogatyy, sorry for the slow response. Our prover is currently tuned for an instance that uses ~128GB of RAM. To make it work best for your particular machine, you should adjust the `SHARD_SIZE` parameter as described here: https://succinctlabs.github.io/sp1/generating-proofs/advanced.html#performance.

This parameter controls how much computation will try to prove in each proof.

**Comment by GraphicalDot** [comment]
Thanks for the clarification.
Sorry for being naive here, Is there a documentation where we can read more about shard_sizes?
