### ISSUE TITLE
Bytes IO result in verification failed: NonZeroCumulativeSum

### ISSUE THREAD

**Issue by akalmykov** [succinctlabs/sp1#459]
When I'm trying to write some bytes 

```rust
let mut stdin = SP1Stdin::new();
let n = [1, 2, 3];
stdin.write_slice(&n);
```
and then read them like this

```rust
let n = sp1_zkvm::io::read_vec();
```
I get the following error:

```
thread 'main' panicked at src/main.rs:34:38:
verification failed: NonZeroCumulativeSum
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: btc_sp1_script::main
``````

A repo to reproduce (a slight modification to the quickstart example): https://github.com/akalmykov/btc_sp1

```
cargo prove --version
cargo-prove sp1 (14bd4b2 2024-03-30T00:16:34.204221449Z)
```

Ubuntu 22.04, x86

**Comment by delehef** [comment]
@akalmykov I encountered the same issue a couple of days ago, but it seems to be fixed on the latest master; probably worth a try!

**Comment by jtguibas** [comment]
Hi, yes this should work on the recent merges to main. Unfortunately sometimes bad stuff gets merged, we're activiely working on better CI that will fix this.
