### ISSUE TITLE
SP1Verifier::verify panics

### ISSUE THREAD

**Issue by JulianGCalderon** [succinctlabs/sp1#468]
If the elf is invalid (bad serialization) `SP1Verifier::verify` panics in [core/src/disassembler/elf.rs](https://github.com/succinctlabs/sp1/blob/850d834e90ce4567bb72c2804d1efe2989c12f9a/core/src/disassembler/elf.rs).

Is this the intended behaviour? if it is, is there a way to check if an elf is valid before verifying in order to avoid panicking?

**Comment by jtguibas** [comment]
This has been resolved in the latest branch of `dev`.
