### ISSUE TITLE
SP1 version is not pinned when running `cargo prove new`, leading to errors

### ISSUE THREAD

**Issue by MauroToscano** [succinctlabs/sp1#513]
SP1 version is not pinned when running `cargo prove new`, and uses the current version of main.

This is leading to compilation errors right now when following the tutorial. Manually pinning the `sp1-zkvm`makes it work again. Maybe it should be pinned by default.

**Comment by ratankaliani** [comment]
Hi! We've added testing for this such that it should always work on main, but thank you for flagging.
