### ISSUE TITLE
Proof format

### ISSUE THREAD

**Issue by makiv2** [succinctlabs/sp1#569]
What exactly is the format of the data field in the json proof file generated after creating a proof?

I would like to be able to extract values. My assumption was that it looks like a Vec<u8>, which should be decoded with String::from_utf8() but I do not have any luck with this.

A pointer on what to do or some documentation about the proof structure would super helpful if this exists, I could not find it on the page.

**Comment by Levike34** [comment]
Adding onto this, it would also be great to know how to extract a proof from file path to use in verification as well. I could not find any tool for this in the sdk.

**Comment by makiv2** [comment]
After doing some digging I found out that the bytearray under the data field does not encode properly only if the arguments being passed are longer than 332 characters. I will try to look more into this and see if there is an issue with my elf or if this potentially is a bug.
