### ISSUE TITLE
Proofs created using different ELF files still pass with client.verify(ELF, proof)

### ISSUE THREAD

**Issue by Levike34** [succinctlabs/sp1#596]
Steps to reproduce:

1. Create proof using fibonacci example and write to file "proof-with-io.json"
2. Change fibonacci example to another program, ex) change the addition to multiplication to generate NEW_ELF
3. Pass NEW_ELF and load old proof from file from no. 1:
`
client.verify(NEW_ELF, &proof).expect("verification failed)
`

This always returns (). I think this should return true/false, and this case above should return false

**Comment by ratankaliani** [comment]
Hey @Levike34, thanks for raising this! Your issue be resolved in the following PR: https://github.com/succinctlabs/sp1/pull/580

We are in the process of changing our SDK API's & they should be more stable soon.

**Comment by Levike34** [comment]
@ratankaliani now I cannot get it to work at all, it always fails on client.setup. It fails with 'Segmentation Fault', or 'Invalid input vecs for input stream' in my warp server setup.  It was working before this new format.
