### ISSUE TITLE
[docs] Add a markdown to each precompile specifying some overall performance numbers

### ISSUE THREAD

**Issue by ValarDragon** [succinctlabs/sp1#722]
Its a bit hard to understand the precompile costs right now, when skimming through the repo. I think we could boost our ability to improve precompiles by standardizing on some simple type of markdown file, which lists out:
- Num columns
- num rows

(or alternatively total trace area) per call.

When were writing the precompile, surely we already see this. (Inspired by trying to grok this from the Blake3 code)

**Comment by ratankaliani** [comment]
Hey @ValarDragon, we recently added a notion of SP1 gas which estimates the cost per precompile "cycle" based on the relative trace area. You can see the implementation here: https://github.com/succinctlabs/sp1/blob/8a62caa0b8893aabe8e9477d4568c20387ae4896/crates/core/machine/src/riscv/cost.rs

We expose this in the `sp1-sdk` on the `ExecutionReport` with `fn estimate_gas`.
