### ISSUE TITLE
Benchmark and accelerate `bn254` precompiles in `revm` 

### ISSUE THREAD

**Issue by puma314** [succinctlabs/sp1#723]
**Background**: `revm` uses the [`substrate-bn` crate](https://github.com/bluealloy/revm/blob/d185018d33fd73a880eaa54bdcd6e463f8a6d11a/crates/precompile/Cargo.toml#L25C1-L26C1) for implementing the `bn254` pairing precompile in EVM. 

We recently added a syscall [`sys_bigint`](https://github.com/succinctlabs/sp1/blob/2f57e1e77f7c88396b571bd961d3cbe4b1291c7a/zkvm/precompiles/src/bigint_mulmod.rs#L9) that precompiles `uint256` `mulmod` and can be used to accelerate `bn254` computations.

- [ ] Profile `revm` `bn254` precompiles (`add`, `mul`, `pairing`) zkVM performance by writing an example program (can use one of their [test vectors](https://github.com/bluealloy/revm/blob/d185018d33fd73a880eaa54bdcd6e463f8a6d11a/crates/precompile/src/bn128.rs)) that uses the various bn254 precompiles and looking at the cycle count. 
- [ ] Patch `substrate-bn`: https://github.com/paritytech/bn to use our `sys_bigint` precompile (or other existing `bn254` precompiles, we have ones for `add` and `double` [here](https://github.com/succinctlabs/sp1/blob/2f57e1e77f7c88396b571bd961d3cbe4b1291c7a/zkvm/precompiles/src/bn254.rs#L9)) to accelerate its performance
- [ ] Benchmark reduced cycle count of example programs

**Comment by shadrach-tayo** [comment]
@puma314 Should the revm profiling example code be done here or in the revm codebase?

**Comment by m-kus** [comment]
I got some rough numbers (single sample) generated with https://github.com/m-kus/sp1-bn254-benchmark

| Operation | # cycles |
| - | - |
| G1 addition | 30,034 |
| G1 multiplication | 1,735,257 |
| G2 addition | 104,122 |
| G2 multiplication | 31,221,329 |
| Miller loop | 33,175,157 |
| Final exponentiation | 45,323,747 |

Substrate BN is widely used (and will) and ZK friendliness might not be enough incentive to swap to arkworks I guess, given that it's extra work (I might be wrong). It is still possible to speed up Montgomery mults with bigint syscall I believe, maybe also worth considering adding a Montgomery specific precompile?

**Comment by brozorec** [comment]
I got similar results when using `substrate-bn`. I tried `arkworks` as is, and also patched it by using [this](https://github.com/arkworks-rs/algebra/compare/master...NebraZKP:algebra:v0.4.2-risc0) approach (mentioned above) that relies on the `mulmod` precompile.

Here are the results (copied the table from @m-kus for a better comparison):

| Operation | substrate-bn | arkworks | arkworks (patched) |
| --------------| ----------------- | -------------| ------------------------- |
| G1 decoding (uncompressed) | 10,194 | n/a | n/a |
| G1 encoding | 119,182 | n/a | n/a |
| G1 addition | 30,034 | 17,134 | 3,964 |
| G1 multiplication | 1,735,257 | 4,494,212 (?) | 918,631 |
| G2 decoding (uncompressed) | 27,958,488 | n/a | n/a  |
| G2 encoding | 162,243 | n/a | n/a |
| G2 addition | 104,122 | 49,403 | 17,109 |
| G2 multiplication | 31,221,329 | 13,965,273 | 4,667,998 |
| Miller loop | 33,175,157 | 16,487,911  | 6,391,641 |
| Final exponentiation | 45,323,747 | 16,875,843 | 8,165,645 |

Note: there's a precompile for sw points addition, and when using it directly, the cycle count for "G1 addition" drops to ~1k.

I'll post a link to the benchmark repo in the next days.

**Comment by m-kus** [comment]
I was able to patch `substrate-bn` and switch from Montogomery form to the plain representation while keeping the same API. The intermediate results are:

| Operation | substrate-bn | substrate-bn-sp1 (patched) |
| - | - | - |
| G1 decoding (uncompressed) | 10,194 | 2,151 |
| G1 encoding | 119,182 | 101,621 |
| G1 addition | 30,034 | 5,301 |
| G1 multiplication | 1,735,257 |  402,823 |
| G2 decoding (uncompressed) | 27,958,488 | 8,456,595 |
| G2 encoding | 162,243 | 118,227 |
| G2 addition | 104,122 | 34,501 |
| G2 multiplication | 31,221,329 | 9,373,338 |
| Miller loop | 33,175,157 | 10,218,611 |
| Final exponentiation | 45,323,747 | 15,732,468 |

Patched `substrate-bn` crate: https://github.com/m-kus/substrate-bn-sp1/pull/1

There are some things left to optimized yet (e.g. constants are still in the Montogomery form) so the final numbers will probably be a bit smaller.

**Comment by jtguibas** [comment]
We are working on this internally...
