### ISSUE TITLE
Invalid Poseidon2 Chip Test Case

### ISSUE THREAD

**Issue by nyunyunyunyu** [succinctlabs/sp1#743]
The test case of Poseidon2 Chip seems invalid. I replaced the expected outputs with some random values and the test could still passed. Not sure if the circuit is under-constrained or the implementation has bugs.

Codes to reproduce: https://github.com/succinctlabs/sp1/pull/742

**Comment by kevjue** [comment]
@nyunyunyunyu - Thanks for reporting this.  This issue is fixed in this [PR](https://github.com/succinctlabs/sp1/pull/747).

There was an issue with how one of the round flags was set.  We actually knew of this issue and this was on our list of items to address before our production release.
