### ISSUE TITLE
Bug: underconstrained uint256_div

### ISSUE THREAD

**Issue by 0xLogos** [succinctlabs/sp1#746]
[Here](https://github.com/succinctlabs/sp1/blob/f50fb1c3b11993fa926c128b1d38db7af969ef51/zkvm/precompiles/src/uint256_div.rs#L53C59-L53C68) only `quotient * y == x - remainder` is constrained, I believe `0 <= remainder < y` should be constrained as well.

**Comment by jtguibas** [comment]
Fixed in #915
