### ISSUE TITLE
Improve CLI

### ISSUE THREAD

**Issue by zemse** [succinctlabs/sp1#814]
Currently, there are some steps involved to generate proof in toy project setup done using `cargo prove new`

1. `cd program`
2. `cargo prove build`
3. `cd ../script`
4. `cargo run --release`

It would be great if a command like `cargo prove` done in top-level projects would do the above tasks, hereby improving the dev ex.

Related https://github.com/succinctlabs/sp1/issues/248

**Comment by ratankaliani** [comment]
Hey @zemse! Thanks for raising this issue, we added a feature a few months ago automatically builds the program when you call `cargo run --release` in the script directory using a build file that wasn't documented in the quickstart. The above PR updates that in the documentation, but you can use that already today.
