### ISSUE TITLE
Go / macOS CoreFoundation link error when building `gnark-ffi`

### ISSUE THREAD

**Issue by Baltoli** [succinctlabs/sp1#841]
I am unable to build the crate `sp1-recursion-gnark-ffi` in `recursion/gnark-ffi` on macOS because of (what appears to me to be) an issue with the object files built by Go / CGo.

System information:
* macOS 14.5
* SDK (`xcrun --show-sdk-path`): `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`
* Rust installed via Rustup (`cargo 1.79.0-nightly (48eca1b16 2024-04-12)`)
* Go installed via Homebrew (`go version go1.22.3 darwin/arm64`)

Steps to reproduce:
```console
$ git clone git@github.com:succinctlabs/sp1.git
$ cd sp1/recursion/gnark-ffi
$ cargo test --release
... omitted ...
            _SecTrustGetCertificateAtIndex, referenced from:
                _runtime.text in libsp1gnark.a[2](go.o)
            _SecTrustGetCertificateCount, referenced from:
                _runtime.text in libsp1gnark.a[2](go.o)
            _SecTrustSetVerifyDate, referenced from:
                _runtime.text in libsp1gnark.a[2](go.o)
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: could not compile `sp1-recursion-gnark-ffi` (lib test) due to 1 previous error
```

**Comment by ratankaliani** [comment]
Hey @Baltoli, this PR: https://github.com/succinctlabs/sp1/pull/842 should fix that in the next official release! 

We're also working on using Docker for PLONK proving so developers won't need to have Go installed on their machine to do the PLONK proving. 

You should be able to build the crate and use the `sp1-sdk` with no issues, as the PLONK proving is gated behind the `plonk` feature flag.
