### ISSUE TITLE
Fibbonacci problem (fresh from sp1-template) OOMs when proving

### ISSUE THREAD

**Issue by color-typea** [succinctlabs/sp1#867]
**Problem:** Running fibbonacci - freshly cut from sp1-project-template, no modifications at all - crashes due to out of memory.

**Steps to reproduce:**

```
git clone git@github.com:succinctlabs/sp1-project-template.git
cd sp1-project-template/script
RUST_LOG=debug cargo run --bin prove --release
```

Expected result: generates proof and writes it to `contracts/src/fixtures`
Actual result: runs for ~3-4 minutes (fluctuates) and get killed by OOM.

**Additional info:**
* System spec: i7-14700HX + 32Gb DDR5 5600MHz RAM, Ubuntu 24.04
* Tried increasing swap to ~80Gb - below 64Gb it just get killed, but runs progressively longer (~15min for 32Gb swap + 32Gb RAM). Above 64Gb it still gets killed, and for some reason takes login shell with it :) (so I'm also logged out, window server restarts, etc.)
* Setting FRI_QUERIES=1 seems to solve the problem, peak memory consumption somewhere ~20Gb (wasn't keeping a close eye)
* Switching to `prove` or `prove_compressed` (+commenting out fixture generation) also solves the problem

**Toolchain versions:**
* sp1-project-template: 9d5e2939f962d884b1505e1dc10fe6b36a7aff95
* sp1: v0.1.0 (https://github.com/succinctlabs/sp1.git?tag=v1.0.4-testnet#2ce75c6e)
* cargo prove: cargo-prove sp1 (1db2197 2024-05-11T00:08:22.023824474Z)

**Comment by ratankaliani** [comment]
The most recent release of `sp1-project-template` should work any machine with ~16 GB RAM.

More info can be found in this issue description: https://github.com/succinctlabs/sp1-project-template/issues/5
