### ISSUE TITLE
Plonk bn254 artifacts take extremely long time to load

### ISSUE THREAD

**Issue by color-typea** [succinctlabs/sp1#868]
**Problem:** bn254 artifacts take extremely long to download:

```
[sp1] plonk bn254 artifacts for commit 57ad9e7d do not exist at ~/.sp1/circuits/plonk_bn254/57ad9e7d. downloading...
2024-06-01T09:32:51.945074Z DEBUG starting new connection: https://sp1-circuits.s3-us-east-2.amazonaws.com/    
2024-06-01T09:32:51.945871Z DEBUG resolving host="sp1-circuits.s3-us-east-2.amazonaws.com"
2024-06-01T09:32:51.967406Z DEBUG connecting to 3.5.131.121:443
2024-06-01T09:32:52.328139Z DEBUG connected to 3.5.131.121:443
⠈ [00:20:03] [##>------------------------------------------------------------------------------------] 129.95 MiB/4.30 GiB (45.03 KiB/s, 27h)
```

**Note:** I'm not in the US. But ~50Kb/s download speed is definitely not normal in year 2024 :)
**Note 2:** obviously, I have checked it's not my wifi/network/ISP causing this.

Also: I could build it from source... but the commit in question doesn't seem to belong to any published branch:
https://github.com/succinctlabs/sp1/commit/57ad9e7d

**Comment by jtguibas** [comment]
Hi, that's weird. It's hosted on AWS so the download should be quite fast. In the future, we plan to ship a docker container which should have a CDN based download system.
