### ISSUE TITLE
Question about the `secp256k1::verify_signature` in precompiles

### ISSUE THREAD

**Issue by xiyu1984** [succinctlabs/sp1#979]
Hi,

I made a simple test of the `secp256k1::verify_signature` in precompiles. I found the [verify_signature](https://github.com/succinctlabs/sp1/blob/14eb569d41d24721ffbd407d6060e202482d659c/zkvm/precompiles/src/secp256k1.rs#L79) errors but the native [ecdsa verify](https://github.com/xiyu1984/sp1-cook/blob/01380b3516ce949c16dee84a68b7bcbf6bcfe9cf/program/src/cooks/verify_ecdsa.rs#L26) successes.

The code in the program is [here](https://github.com/xiyu1984/sp1-cook/blob/main/program/src/cooks/verify_ecdsa.rs).

```rs
use sp1_precompiles::secp256k1::verify_signature;
use tiny_keccak::{Hasher, Keccak};
use k256::ecdsa::Signature;
// use k256::{ecdsa::{Signature, VerifyingKey, signature::Verifier}, PublicKey};

pub fn verify_ecdsa() {
    let msg_bytes = sp1_zkvm::io::read_vec();
    let mut hasher = Keccak::v256();
    hasher.update(&msg_bytes);
    let mut msg_digest = [0u8; 32];
    hasher.finalize(&mut msg_digest);
    // println!("circuit hash: {:?}", msg_digest);

    let pk_slice: [u8; 65] = sp1_zkvm::io::read_vec().try_into().expect("circuit reading pk error");

    let signature_vu8: [u8; 64] = sp1_zkvm::io::read_vec().try_into().expect("circuit reading signature error");
    let signature: Signature = Signature::from_slice(&signature_vu8).expect("circuit construct signature error");
    
    // `verify_signature` errors
    assert!(verify_signature(&pk_slice, &msg_digest, &signature, None), "Invalid signature");

    // The below is ok
    // let public_key = PublicKey::from_sec1_bytes(&pk_slice);
    // let public_key = public_key.unwrap();
    // let verify_key = VerifyingKey::from(&public_key);
    // assert!(verify_key.verify(&msg_digest, &signature).is_ok(), "executing verification fialed!");
}
```

And the code in scripts is [here](https://github.com/xiyu1984/sp1-cook/blob/main/script/src/bin/prove_ecdsa.rs).

I'd like to know if I made any mistakes when calling `secp256k1::verify_signature`.

I run the script by
```sh
cd script
RUST_LOG=info cargo run --bin prove_ecdsa --release
```

**Comment by jtguibas** [comment]
Btw, I get the following

```
~/Desktop/sp1-cook/script (main) » RUST_LOG=info cargo run --bin prove_ecdsa --release
error: failed to load manifest for dependency `plonky2_field`

Caused by:
  failed to read `/Users/jtguibas/zkp/plonky2/field/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
```

I guess I need to have Plonky2 in the right path

**Comment by jtguibas** [comment]
Also noticing you have custom forks for sp1-sdk, and sp1-helper, do I need to use those forks?

**Comment by xiyu1984** [comment]
> Also noticing you have custom forks for sp1-sdk, and sp1-helper, do I need to use those forks?

It's just the same as the main branch of `sp1` (the newest).

BTW, I think I found the problem. `erify_key.verify` is different from the `erify_key.verify_prehash` and the implementation of `secp256k1::verify_signature` follows the implementation of `erify_key.verify_prehash`.

**Comment by jtguibas** [comment]
Ah I see. 

In `reth/revm`, we use the Secp256k1 crate like this: https://github.com/sp1-patches/reth/blob/cbe484c16960dea443ecabf2a5ae6070292e9dee/crates/primitives/src/transaction/util.rs#L23-L35.

**Comment by xiyu1984** [comment]
> Ah I see.
> 
> In `reth/revm`, we use the Secp256k1 crate like this: https://github.com/sp1-patches/reth/blob/cbe484c16960dea443ecabf2a5ae6070292e9dee/crates/primitives/src/transaction/util.rs#L23-L35.

Thanks a lot. I have changed the `sign` to `sign_prehash` and everything works well.

[program](https://github.com/xiyu1984/sp1-cook/blob/main/program/src/cooks/verify_ecdsa.rs)
[script](https://github.com/xiyu1984/sp1-cook/blob/ab2958e6ec20df9330f21d59d2db11e450b707f4/script/src/bin/prove_ecdsa.rs#L36)
