### ISSUE TITLE
EVM proving example fails with error

### ISSUE THREAD

**Issue by emo-eth** [succinctlabs/sp1#982]
Running the command `RUST_LOG=info cargo run --bin plonk_bn254 --release` in the `./excamples/fibonacci/scripts/` dir as specified in the [docs](https://docs.succinct.xyz/verifying-proofs/solidity-and-evm.html) results in this error on my machine, after pulling the latest 1.0.8-testnet image:

```
2024-06-26T01:03:03.393274Z ERROR wrap_plonk_bn254: Failed to run `docker run`: "docker" "run" "--rm" "-v" "~/.sp1/circuits/plonk_bn254/v1.0.8-testnet:/circuit" "-v" "/var/folders/0r/z9q3kxg56f16tld0wryghmd00000gn/T/.tmpKlDeg3:/witness" "-v" "/var/folders/0r/z9q3kxg56f16tld0wryghmd00000gn/T/.tmpSLe33r:/output" "ghcr.io/succinctlabs/sp1-gnark:v1.0.8-testnet" "prove-plonk" "/circuit" "/witness" "/output"    
thread 'main' panicked at ~/dev/sp1/recursion/gnark-ffi/src/ffi/docker.rs:51:10:
failed to prove with docker: docker command failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jtguibas** [comment]
Do you have docker installed on your system?

**Comment by jtguibas** [comment]
We should probably print out a better error here. Thanks for making the issue.

**Comment by emo-eth** [comment]
> Do you have docker installed on your system?

yes, docker is up and running – there's a different error if docker isn't running, which i encountered first 🤠

**Comment by mattstam** [comment]
@emo-eth This occurs because the container is running out of memory. Can you try increasing your memory limit for docker (Docker Desktop > Settings > Resources)? Proving plonk locally for this example seems to require ~11GB.

![image](https://github.com/succinctlabs/sp1/assets/15695189/d20d38bb-742c-41bb-b80f-fb42fe906b62)

**Comment by mattstam** [comment]
This is due to the container running out of memory. To prove plonk locally, you need 64GB+ available.

We'll update the docs to reflect these hardware requirements.
