### ISSUE TITLE
Add max cycles parameter to `ProverClient` `{execute, prove}`

### ISSUE THREAD

**Issue by emostov** [succinctlabs/sp1#996]
The caller of `execute` and `prove` should be able to configure a maximum amount of cpu cycles. This is useful in a permissionless setting where resource exhaustion is a concern. For some projects, the lack of this feature will be a hard blocker for adopting sp1

Risc0 already exposes this option: https://docs.rs/risc0-zkvm/latest/risc0_zkvm/struct.ExecutorEnvBuilder.html#method.session_limit

ref: sp1 telegram chat message https://t.me/succinct_sp1/2435

**Comment by jtguibas** [comment]
This has been implemented in #1027. It will be included in the next release. 

Thanks for letting us know about this feature.
